print(2 + 3)
print(3 - 1)
print(2 * 3)
print(3 / 2)
print(3 % 2)
print(3**2)
print(3 // 2)

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(["Asabeneh", "Python", "Finland"]))
print(type("Ibrahim"))
print(type("Abdullahi"))
print(type("Nigeria"))
